name: kids_home1
display_name: kids_home1
version: 1.0.0
author:
  name: "PrestaShop Team"
  email: "pub@prestashop.com"
  url: "http://www.prestashop.com"

meta:
  compatibility:
      from: 1.7.0.0
      to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column

assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
#  use_parent_assets: true

  # The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
#  css:
#    all:
#      - id: custom-lib-style
#        path: assets/css/custom-lib.css
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#  js:
#    cart:
#      - id: cat-extra-lib
#        path: assets/js/cart-lib.js


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
   to_enable:
     - ps_linklist
     - fieldthemecustomizer
     - fieldsizechart
     - fieldblocksearch
     - fieldmegamenu
     - fieldslideshow
     - fieldpopupnewsletter
     - fieldbrandslider
     - fieldblockcategories
     - fieldvmegamenu
     - fieldstaticblocks
     - fieldstaticfooter
     - fieldtabproductsisotope
     - fieldspecialproduct
     - fieldproductcates
     - elevatezoom
     - fieldtabcateslider
     - fieldonecateproductslider
     - smartblog
     - smartbloghomelatestnews
     - smartblogrecentposts
   to_disable:
     - welcome
     - ps_searchbar
     
  hooks:
    modules_to_hook:
      displayAdminProductsExtra:
        - fieldsizechart
      displayBackOfficeHeader:
        - fieldsizechart
        - fieldstaticblocks
        - fieldstaticfooter
        - smartblog
      displayFooter:
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo
        - fieldstaticblocks
        - fieldstaticfooter
      displayFooterBefore:
        - ps_emailsubscription
        - ps_socialfollow
      displayFooterProduct:
        - fieldproductcates
      displayHeaderMenu:
        - fieldmegamenu
      displayHome:       
        - fieldpopupnewsletter
        - fieldstaticblocks
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
        - fieldstaticblocks
        - smartblogrecentposts
      displayLeftColumnProduct:
        - fieldsizechart
      displayMobileTopSiteMap:
        - fieldblocksearch
      displayNav:
        - fieldstaticblocks
      displayNav1:
        - ps_customersignin
      displayNav2:
        - ps_languageselector
        - ps_currencyselector
      displayProductAdditionalInfo:
        - ps_sharebuttons
        - fieldsizechart
      displayProductSizeGuide:
        - fieldsizechart
      displayReassurance:
        - blockreassurance
      displayRightColumn:
        - fieldspecialproduct
        - fieldstaticblocks 
      displayRightColumnProduct:
        - fieldsizechart
      displaySmartBlogLeft:
        - smartblogrecentposts
      displayTop:
        - ps_shoppingcart
        #- fieldblocksearch
        #- fieldstaticblocks

  image_types:
    cart_default:
      width: 721
      height: 800
      scope: [products]
    small_default:
      width: 721
      height: 800
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 721
      height: 800
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 370
      height: 410
      scope: [products]
    large_default:
      width: 721
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 300
      height: 300
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]
    field_manufacture:
      width: 169
      height: 104
      scope: [manufacturers]

theme_settings:
  default_layout: layout-full-width
  layouts:
    best-sales: layout-left-column
    contact: layout-left-column
    manufacturer: layout-left-column
    new-products: layout-left-column
    prices-drop: layout-left-column
    search: layout-left-column
    product: layout-right-column
    category: layout-left-column
    module-smartblog-archive: layout-left-column
    module-smartblog-category: layout-left-column
    module-smartblog-details: layout-left-column
    module-smartblog-search: layout-left-column
    module-smartblog-tagpost: layout-left-column
